CREATE TABLE chat( 
      id  integer generated by default as identity     NOT NULL , 
      usuario_chat_id integer    NOT NULL , 
      mensagem blob sub_type 1   , 
      criada_em timestamp   , 
 PRIMARY KEY (id)) ; 

CREATE TABLE usuario_chat( 
      id  integer generated by default as identity     NOT NULL , 
      sistema blob sub_type 1   , 
      system_user_id integer   , 
      chat_id blob sub_type 1   , 
 PRIMARY KEY (id)) ; 

 
  
 ALTER TABLE chat ADD CONSTRAINT fk_chat_1 FOREIGN KEY (usuario_chat_id) references usuario_chat(id); 
